apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: apptest
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/jgarciaes/argocd.git
    targetRevision: HEAD
    path: apptest
  destination:
    server: https://kubernetes.default.svc
    namespace: apptest
  syncPolicy:
    syncOptions:
      - CreateNamespace=true

    automated: 
      selfHeal: true
      prune: true